### ISSUE TITLE
CSS Error (border extends all the way down the page) in WordPress 3.9

### ISSUE THREAD

**Issue by davidbarratt** [flymke/mark-posts#22]
There seems to be a CSS Error in WordPress 3.9 that causes the border to be extended all the way up and down the page. :(

![mark-posts](https://cloud.githubusercontent.com/assets/868364/2817342/1d432e9e-ced8-11e3-87fa-392175a0f590.png)

Thanks!

**Comment by flymke** [comment]
Hi David,

Can you let us know which version are you using? I currently cannot reproduce the error with 3.9 and 1.0.5. Also can you send us a list of other plugins you are using that might be conflicting?

For a quick fix try to uncomment following line in admin/assets/js/markposts.js:

markposts.js, line 35:

```
// $(this).parent().parent().find('.check-column').append('<div class="mark_posts_pre"  ...
```

We'll definitely be looking into this.

Thanks!
Mike

**Comment by davidbarratt** [comment]
@flymke,

This appears to only happen in FireFox.

Thanks!

**Comment by davidbarratt** [comment]
@flymke,

I'm using FireFox 28.

Thanks!

**Comment by flymke** [comment]
Hi David,

that was a good hint, thank you!

I've just added a fix to the repository. You can download or fetch the master from https://github.com/flymke/mark-posts/. I'll also be adding this to the 1.0.6 version.

Thanks again for your help!

Mike

**Comment by davidbarratt** [comment]
@flymke,

Glad I could be of serivce!

Thanks!
